apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w23o6gy4y-python 
  janus-idp.io/tekton: w23o6gy4y-python
  backstage.io/kubernetes-id: w23o6gy4y-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w23o6gy4y-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml